version: '3.7'

networks:
  app-network:
    driver: bridge

services:
  db:
    build: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
